
export const CHANGE_PERSONAL_INFO = 'CHANGE_PERSONAL_INFO';

export const CHANGE_ADDRESS_INFO = 'CHANGE_ADDRESS_INFO';

export const CHANGE_BILLING_INFO = 'CHANGE_BILLING_INFO';

export const UPDATE_PERCENT_COMPLETED = 'UPDATE_PERCENT_COMPLETED';